Workspace nikhil
sugchand/neoview-middle-box pull request #1
Opened 2017-01-04 10:40 UTC by nikhilfusion

2017-01-05 10:49 UTC, sugchand requested changes
Change the files as suggested..

2017-01-05 10:49 UTC, sugchand commented on .gitignore
> +src/nv_midbox_websock/templates/static/bower_components/
Do not add anything in the gitignore.
Its not a good practice.
Either keep those files in the source tree or provide option to install it.

2017-01-05 10:49 UTC, sugchand commented on src/nv_midbox_websock/templates/.bowerrc
> +  "directory": "static/bower_components"
. file?

Do you really think we need to use the bower for packaging? if there is only few file. I would suggest to get rid of the package manager and keep the file in the source tree statically.

2017-01-05 10:49 UTC, sugchand commented on src/nv_midbox_websock/templates/bower.json
> +  "license": "MIT",
why MIT

2017-01-05 10:49 UTC, sugchand commented on src/nv_midbox_websock/templates/static/js/app.js
> +  // $scope.cameraInfo = [
Remove all commented out fields if its not necessary

2017-01-06 18:36 UTC, closed without merging

2017-01-06 18:36 UTC, nikhilfusion commented
close